### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by fawidmer** [adbuerger/pycombina#28]
Hello

First off, I must admit that I am not a Python crack. So it's possible that I'm making a silly rookie mistake - sorry if that's the case! 🙂 
I'm using Windows, so I was following the steps given in https://pycombina.readthedocs.io/en/latest/install.html#install-on-windows-10

I realized that I need to initialize the pybind submodule.

Now, if I run `python .\setup.py install`, I get the following output, which looks good apart from a few warnings:
```
running install
running bdist_egg
running egg_info
writing pycombina.egg-info\PKG-INFO
writing dependency_links to pycombina.egg-info\dependency_links.txt
writing requirements to pycombina.egg-info\requires.txt
writing top-level names to pycombina.egg-info\top_level.txt
reading manifest file 'pycombina.egg-info\SOURCES.txt'
adding license file 'LICENCE.md'
writing manifest file 'pycombina.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
copying pycombina\__init__.py -> build\lib.win-amd64-3.10\pycombina
running build_ext
CMake Deprecation Warning at CMakeLists.txt:20 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19045.
CMake Deprecation Warning at src/pybind11/CMakeLists.txt:8 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- pybind11 v2.10.0
CMake Warning (dev) at src/pybind11/tools/FindPythonLibsNew.cmake:98 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  src/pybind11/tools/pybind11Tools.cmake:50 (find_package)
  src/pybind11/tools/pybind11Common.cmake:180 (include)
  src/pybind11/CMakeLists.txt:200 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done (0.6s)
-- Generating done (0.3s)
-- Build files have been written to: C:/Users/fawidmer/LocalGitRepos/code/pycombina/build/temp.win-amd64-3.10/Release
Microsoft (R) Build Engine version 16.11.1+3e40a09f8 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  _combina_bnb_solver.vcxproj -> C:\Users\fawidmer\LocalGitRepos\code\pycombina\build\lib.win-amd64-3.10\pycombina\_combina_bnb_solver.cp310-win_amd64.pyd

creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\pycombina
copying build\lib.win-amd64-3.10\pycombina\_binary_approximation.py -> build\bdist.win-amd64\egg\pycombina
copying build\lib.win-amd64-3.10\pycombina\_combina_bnb.py -> build\bdist.win-amd64\egg\pycombina
copying build\lib.win-amd64-3.10\pycombina\_combina_bnb_solver.cp310-win_amd64.pyd -> build\bdist.win-amd64\egg\pycombina
copying build\lib.win-amd64-3.10\pycombina\_combina_milp.py -> build\bdist.win-amd64\egg\pycombina
copying build\lib.win-amd64-3.10\pycombina\_combina_sur.py -> build\bdist.win-amd64\egg\pycombina
copying build\lib.win-amd64-3.10\pycombina\__init__.py -> build\bdist.win-amd64\egg\pycombina
creating build\bdist.win-amd64\egg\test
copying build\lib.win-amd64-3.10\test\combina_test.py -> build\bdist.win-amd64\egg\test
copying build\lib.win-amd64-3.10\test\input_test.py -> build\bdist.win-amd64\egg\test
copying build\lib.win-amd64-3.10\test\rounding_test.py -> build\bdist.win-amd64\egg\test
copying build\lib.win-amd64-3.10\test\__init__.py -> build\bdist.win-amd64\egg\test
byte-compiling build\bdist.win-amd64\egg\pycombina\_binary_approximation.py to _binary_approximation.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pycombina\_combina_bnb.py to _combina_bnb.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pycombina\_combina_milp.py to _combina_milp.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pycombina\_combina_sur.py to _combina_sur.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pycombina\__init__.py to __init__.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\test\combina_test.py to combina_test.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\test\input_test.py to input_test.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\test\rounding_test.py to rounding_test.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\test\__init__.py to __init__.cpython-310.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying pycombina.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying pycombina.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying pycombina.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying pycombina.egg-info\not-zip-safe -> build\bdist.win-amd64\egg\EGG-INFO
copying pycombina.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying pycombina.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
writing build\bdist.win-amd64\egg\EGG-INFO\native_libs.txt
creating 'dist\pycombina-0.3.3-py3.10-win-amd64.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing pycombina-0.3.3-py3.10-win-amd64.egg
removing 'c:\users\fawidmer\localgitrepos\code\pycombina\venv\lib\site-packages\pycombina-0.3.3-py3.10-win-amd64.egg' (and everything under it)
creating c:\users\fawidmer\localgitrepos\code\pycombina\venv\lib\site-packages\pycombina-0.3.3-py3.10-win-amd64.egg
Extracting pycombina-0.3.3-py3.10-win-amd64.egg to c:\users\fawidmer\localgitrepos\code\pycombina\venv\lib\site-packages
pycombina 0.3.3 is already the active version in easy-install.pth

Installed c:\users\fawidmer\localgitrepos\code\pycombina\venv\lib\site-packages\pycombina-0.3.3-py3.10-win-amd64.egg
Processing dependencies for pycombina==0.3.3
Searching for numpy==1.26.1
Best match: numpy 1.26.1
Adding numpy 1.26.1 to easy-install.pth file
Installing f2py-script.py script to C:\Users\fawidmer\LocalGitRepos\code\pycombina\venv\Scripts
Installing f2py.exe script to C:\Users\fawidmer\LocalGitRepos\code\pycombina\venv\Scripts

Using c:\users\fawidmer\localgitrepos\code\pycombina\venv\lib\site-packages
Finished processing dependencies for pycombina==0.3.3
```

However, when I try to run combina_test.py, I get the following error:
```
Failure
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\unittest\suite.py", line 166, in _handleClassSetUp
    setUpClass()
  File "C:\Users\fawidmer\LocalGitRepos\code\pycombina\test\combina_test.py", line 177, in setUpClass
    from pycombina import CombinaBnB
ImportError: cannot import name 'CombinaBnB' from 'pycombina' (C:\Users\fawidmer\LocalGitRepos\code\pycombina\pycombina\__init__.py)
```

Am I missing something? What am I doing wrong?

Thank you for your help!
Fabio

**Comment by mirhahn** [comment]
Hi,

There are quite a few deprecation warnings in there, so we should probably get on that. However, there's a good chance that you're having a common problem with Python import resolution.

When you run the tests, they `import pycombina`, which you would expect to import the version of `pycombina` that you have just installed with `setup.py`. However, you have to remember that the root folder of the repository also contains a folder called `pycombina` that (confusingly) also contains the entire Python code, but does not contain the compiled solver module. That local directory takes precedence in Python's import logic, so you never actually load the installed version if you call `combina_test.py` from the root directory of your working copy.

If I'm correct, it should be okay if you first `cd` to the `test` subdirectory and then invoke `combina_test.py`. This has been a recurring issue that a few of the contributors (including myself) have also fallen for, so no need to feel bad.

Let me know if it works.

**Comment by fawidmer** [comment]
Dear Mirko
Thanks a lot, this was exactly the issue. However, I was not able to make it run by changing the directory. I did manage by simply deleting the `pycombina` source folder. Now, the correct `import` is utilized. Marking the folder "Excluded" in pycharm was also not enough for some reason.
I see that you have been taking this as impetus to rework the setup of the repo - I hope I was not causing you too much trouble. I'm happy to try out the new structure once it's available and give you feedback.
Let me know if there's anything I can be of help.
Fabio

**Comment by mirhahn** [comment]
You're still using `pytest` to run the tests, right? If so, the problem might be that `pytest` messes around with the `sys.path` variable. I think it tries to find the root directory of the project so that the tests can use the module without first having to install it. That's a very good idea for pure Python projects, but it doesn't work for PyCombina because of the missing extension module.

I have found that this command line works for me:
```bash
(cd test; pytest --import-mode importlib .)
```
I work on Linux, so I don't have your exact setup. You might have to translate this into something your shell understands, but I think the idea is pretty clear.

*Note:* I tried this on the current `develop` branch of my own fork, but that should be in line with `develop` on this repository.

**Comment by adbuerger** [comment]
Thank you @mirhahn for your work, the simplified installation process has been merged into the main branch. @fawidmer if you like, please feel free to test the updated instructions provided at https://pycombina.readthedocs.io/en/latest/install.html, and thank you for your interest in pycombina. Please let us know in case you should encounter any further issues

**Comment by fawidmer** [comment]
@adbuerger @mirhahn: I cloned the repo to a separate machine and got everything working by following the installation instructions. Thanks a lot!! 👍

**Comment by adbuerger** [comment]
Great to hear @fawidmer , thanks for letting us know!
